name: Lint and check files

on:
  workflow_call:

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        run: make lint
  check-diagrams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make diagrams
        run: make --always-make diagrams
      - name: Check
        run: |
          if OUTPUT=$(git status --porcelain diagrams) && [ -n "${OUTPUT}" ]; then
            echo "Found generated diagrams that do not match the source:"
            echo "${OUTPUT}"
            false
          fi
